### ISSUE TITLE
Fix generator switch

### ISSUE THREAD

**Issue by rperciaccante** [rperciaccante/HomeAssistant_OneControl_Discovery#10]
entity sensor.onecontrol_generator_command should be be a switch to trigger the generator startup

**Comment by rperciaccante** [comment]
State needs to be split from incoming on/off commands.  OC sends status messages such as "Starting" and "Priming" which does not fit with the Home Assistant expectant values (on or off, etc)

**Comment by rperciaccante** [comment]
Sample from generator actions:
{"type":"String","value":"OFF"}
{"type":"String","value":"PRIMING"}
{"type":"String","value":"STARTING"}

**Comment by ChaseTheRide** [comment]
@rperciaccante are you still looking at needing this tested?  I can test it tomorrow for you if needed.
