### ISSUE TITLE
Before looking around I need to know your license.  

### ISSUE THREAD

**Issue by spbrogan** [rperciaccante/HomeAssistant_OneControl_Discovery#15]
Can you document your license terms?  
I would love to look around and potentially collaborate on some stuff here.  Especially how you modeled devices in the RV and MQTT format.  

I have just started doing something similar using the RVC canbus interface in my keystone cougar. 
https://github.com/spbrogan/rvc2mqtt

But I don't want to run afoul of license terms and my project was derived off of a previous github project which was apache 2 licensed.  At the moment i have no commercial plans and any and all changes I am happy to share publicly but i just steer away from GPL licenses as they introduce restrictions that are more complicated.

**Comment by rperciaccante** [comment]
Sure!  It is under the Apache 2.  Sorry, I will update that in the repo.

 

Bob

 

 

From: Sean Brogan ***@***.***> 
Sent: Wednesday, January 12, 2022 4:42 PM
To: rperciaccante/HomeAssistant_OneControl_Discovery ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rperciaccante/HomeAssistant_OneControl_Discovery] Before looking around I need to know your license. (Issue #15)

 

Can you document your license terms?
I would love to look around and potentially collaborate on some stuff here. Especially how you modeled devices in the RV and MQTT format.

I have just started doing something similar using the RVC canbus interface in my keystone cougar.
https://github.com/spbrogan/rvc2mqtt

But I don't want to run afoul of license terms and my project was derived off of a previous github project which was apache 2 licensed. At the moment i have no commercial plans and any and all changes I am happy to share publicly but i just steer away from GPL licenses as they introduce restrictions that are more complicated.

**Comment by spbrogan** [comment]
thanks
