### ISSUE TITLE
Devices not getting detected after updating HA.

### ISSUE THREAD

**Issue by JoshWobbles** [rperciaccante/HomeAssistant_OneControl_Discovery#32]
I updated HA to 8.4 and had to reinstall this flow due to switching to a new storage card, now its not picking up all the devices, i only see the 1 device and 5 entities that are there by default and nothing related to my trailer.

**Comment by rperciaccante** [comment]
> 

When you look at Node Red, are there any nodes that are greyed out?  Also, if you go to the "OneControl Monitoring" flow, there is a manual flow connection trigger on the upper left.  Please try this to restart the flows.

**Comment by JoshWobbles** [comment]
No grayed out nodes. I clicked the "manual Events connection " button but see no difference

**Comment by rperciaccante** [comment]
can you provide a screen shot?  Any errors in the HA log?

**Comment by JoshWobbles** [comment]
![Screenshot_20220803-165211_Edge](https://user-images.githubusercontent.com/18446288/182713405-cf565a55-767a-46fd-945f-0b1a11800ee8.jpg)
No errors a says connected in the flows

**Comment by rperciaccante** [comment]
Please show screenshot from "OneControl Monitoring".  Did you click on the re-discovery?

**Comment by JoshWobbles** [comment]
Actually I restored a backup from before the os update and that seemed to fix it, not sure where the hiccup happened but seems OK now.
