### ISSUE TITLE
Is this still under development? Or has it been abandoned?

### ISSUE THREAD

**Issue by ralbright-wa** [rperciaccante/HomeAssistant_OneControl_Discovery#37]
Is this still under development or has it been abandoned? I am wanting to add this to my travel trailer, And have gotten a lot of things changed in my home assistant setup, including hooking up the mini-PC to my 12V system through a regulated 19V output boost converter.

This is the next logical step, but I need to know what needs to be purchased to make this happen. Now that Lippert has the ConnectAnywhere system, and their app runs via Bluetooth, wanting to see if this could be modified to run from that? OR what devices need to be purchased to integrate this entirely.

**Comment by rperciaccante** [comment]
This project is on hold until I can get the cloud bridge installed into my new RV.

This project, however, has only ever been interacting with the OneControl Cloud Controller, which runs a version of OpenHab.  The OpenHab platform provides all the API calls that are needed for the integration with Home Assistant/Node Red.  You would not be able to leverage this integration over bluetooth as OpenHab is not used for the bluetooth version (as far as I know).

If you want to leverage the existing project, you will need a Lippert Cloud Gateway https://store.lci1.com/onecontrol-cloud-gateway-assembly-711151. This came installed on many RV's from the factory, but when the Raspberry Pi became hard to source, they stopped including them in the RV's.  If you can find one on eBay, or elsewhere, you would be able to use this integration with your RV.

**Comment by ralbright-wa** [comment]
Aside from the Cloud Gateway Assembly, what other items are required? I recently purchased the MyRV Gateway Hub that came with the router assembly. I am not really wanting to utilize the router, as I already have a Pepwave MAX BR1 MK2 LTEA installed with my starlink and a Poynting 5-in-1 antenna installed. And suggestions would be greatly appreciated. Thank you.

**Comment by rumlak** [comment]
If you join the diy smart rv Facebook group there is a pdf in the files section that walks you thru bypassing the lci router.  I used those but ran an Ethernet cable to it so I did't need to use a WiFi repeater.

**Comment by rumlak** [comment]
Also recommend joining the discord group also.

**Comment by rperciaccante** [comment]
> 

Correct. The cloud gateway is not the wireless bridge, it is a component that acts as a bridge between the IP network and canbus (LCI part number 711151), and still requires a wireless gateway to act as a router. I am the admin in both the DIY Smart RV Facebook group as well as the Discord.

**Comment by ralbright-wa** [comment]
Thank you. I do have a few precious Raspberry Pi 4s in my home that are sitting ideal that could be converted for this use. Or I could just break down and purchase it from LCI... I also found the DIY Smart RV a few days ago and joined it. Thank you!!!

**Comment by rperciaccante** [comment]
The raspberry Pi is used in the Cloud Controller with proprietary code and a custom Canbus interface card.
